version: "3.9"

services:
  app:
    image: pearhub-backend_app:latest
    container_name: pearhub-backend_app
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: pearhub-backend_nginx
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default

  db:
    image: postgres:17
    container_name: pearhub-backend_db
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - default

networks:
  default:

volumes:
  db_data: